#!/usr/bin/env bash
# Regenerate tests/CATALOGUE.md from the test files themselves.
#
#   ./tests/catalogue.sh            # write tests/CATALOGUE.md
#   ./tests/catalogue.sh --check    # exit 1 if it is out of date (CI uses this)
#
# Hand-maintaining a list of 118 tests would be wrong within a week, so the
# catalogue is derived: test names come from `@test "..."`, the per-suite blurb
# from each file's header comment, and the provenance column from `# guards:`
# annotations placed directly above a test. Same shape as
# `build-audit.sh --freeze` for patches/SERIES.sha256.
set -euo pipefail
# The generated file is compared byte-for-byte by `--check`, so every sort below
# has to order the same way everywhere. Without a pinned locale it does not: a
# UTF-8 collation ignores punctuation at the first level and orders "wins, even
# with no primary line" before "wins when it is marked non-primary", while C
# compares bytes and puts the space before the comma, reversing them. The
# catalogue then passes on the machine that wrote it and fails on the runner.
# Same reason install.sh and make-installer.sh pin it.
export LC_ALL=C.UTF-8
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
cd "$root"

OUT="tests/CATALOGUE.md"

# Suites in the order CI runs them: cheapest and most-likely-to-fail first.
SUITES=(
    tests/repo-hygiene.bats
    tests/packaging.bats
    tests/launcher-cli.bats
    tests/unit/detect-scale.bats
    tests/unit/detect-theme.bats
    tests/unit/launcher.bats
    tests/patch-stack.bats
)

# The list above is hand-ordered on purpose (CI order, not alphabetical), which
# means a new suite has to be added by hand — and a suite left out is invisible
# to both the catalogue and `--check`, so the document keeps passing while it
# quietly stops describing the tests it claims to. Fail instead: a catalogue
# that reads complete and is not is the failure mode this file exists to avoid.
missing=()
while IFS= read -r f; do
    case " ${SUITES[*]} " in *" $f "*) ;; *) missing+=("$f") ;; esac
done < <(find tests -name '*.bats' | sort)
if [ "${#missing[@]}" -gt 0 ]; then
    printf '!! suite missing from SUITES in %s: %s\n' "$0" "${missing[*]}" >&2
    exit 1
fi

# The file header: contiguous comment lines after the shebang, minus the "#".
suite_blurb() {
    awk 'NR==1 && /^#!/ { next }
         /^#/ { sub(/^# ?/, ""); print; next }
         { exit }' "$1"
}

generate() {
    local total=0 f n
    for f in "${SUITES[@]}"; do
        n="$(grep -c '^@test ' "$f" || true)"
        total=$((total + n))
    done

    cat <<EOF
# Test catalogue

Every test in the suite, what it covers, and where the behaviour came from.

**Generated by \`tests/catalogue.sh\` — do not edit by hand.** Test names come
from the files, and the *Guards* column from \`# guards:\` annotations above a
test. Run \`./tests/catalogue.sh\` after adding or renaming a test;
\`tests/repo-hygiene.bats\` fails when this file is stale.

$total tests across ${#SUITES[@]} suites. See [README.md](README.md) for how to run
them and [../.github/workflows/ci-checks.yml](../.github/workflows/ci-checks.yml)
for which run on a PR.

## Contents

EOF
    local f name
    for f in "${SUITES[@]}"; do
        name="$(basename "$f" .bats)"
        printf -- '- [%s](#%s) — %s test(s)\n' \
            "$f" "$(printf '%s' "$name" | tr -cd 'a-z0-9-')" "$(grep -c '^@test ' "$f" || true)"
    done

    for f in "${SUITES[@]}"; do
        name="$(basename "$f" .bats)"
        printf '\n<a id="%s"></a>\n\n## %s\n\n' \
            "$(printf '%s' "$name" | tr -cd 'a-z0-9-')" "$f"
        suite_blurb "$f" | sed 's/^$//'
        printf '\n| # | Test | Guards |\n| --- | --- | --- |\n'
        awk '
            /^# guards: / { g = substr($0, 11); next }
            /^@test / {
                line = $0
                sub(/^@test "/, "", line)
                sub(/" \{[ \t]*$/, "", line)
                gsub(/\|/, "\\|", line)
                gsub(/\|/, "\\|", g)
                n++
                printf "| %d | %s | %s |\n", n, line, (g == "" ? "—" : g)
                g = ""
                next
            }
            /^[^#[:space:]]/ { g = "" }
        ' "$f"
    done

    # Reverse index: only entries that actually appear in a guards annotation.
    printf '\n## Cross-reference\n\nIssues, commits and source sites cited by a `# guards:` annotation.\n\n'
    printf '| Reference | Tests |\n| --- | --- |\n'
    {
        for f in "${SUITES[@]}"; do
            awk -v suite="$(basename "$f" .bats)" '
                /^# guards: / { g = substr($0, 11); next }
                /^@test / {
                    if (g != "") {
                        line = $0
                        sub(/^@test "/, "", line); sub(/" \{[ \t]*$/, "", line)
                        # Leading token up to the em dash is the reference.
                        ref = g
                        sub(/ —.*$/, "", ref)
                        printf "%s\t%s: %s\n", ref, suite, line
                    }
                    g = ""
                    next
                }
                /^[^#[:space:]]/ { g = "" }
            ' "$f"
        done
    } | sort | awk -F'\t' '
        { if ($1 != prev) { if (prev != "") printf "%s |\n", acc; printf "| `%s` | ", $1; acc = ""; prev = $1 }
          acc = acc (acc == "" ? "" : "<br>") $2 }
        END { if (prev != "") printf "%s |\n", acc }'
}

if [ "${1:-}" = --check ]; then
    if ! diff -u "$OUT" <(generate) >/dev/null 2>&1; then
        echo "!! $OUT is out of date — run ./tests/catalogue.sh" >&2
        diff -u "$OUT" <(generate) >&2 || true
        exit 1
    fi
    echo "OK: $OUT is current"
    exit 0
fi

generate > "$OUT"
echo "OK: wrote $OUT ($(grep -c '^| [0-9]' "$OUT") tests)"
